# Generated by Django 4.2.30 on 2026-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_ru',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_uz_cyr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_uz_cyr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='description_uz_cyr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='test',
            name='title_uz_cyr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
